"""Install VISET, load your sets, and credit the projects it builds on.

Docs: https://mnicolee.github.io/VISET/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_core.ipynb.

# %% auto #0
__all__ = ['load']

# %% ../nbs/03_core.ipynb #c81b68f3
import pandas as pd

# %% ../nbs/03_core.ipynb #b4b78d36
def load(path, col, label):
    "Read `col` from the CSV at `path`, drop NaNs, and return a one-column DataFrame named `label`."
    return pd.read_csv(path)[col].dropna().rename(label).to_frame()
